# See https://aka.ms/devcontainer for more info
FROM mcr.microsoft.com/devcontainers/python:latest

# Install any additional OS packages you need here
# RUN apt-get update && apt-get install -y <package-name>

# [Optional] Install additional Python packages
# RUN pip install <package-name>

# [Optional] Set up non-root user if needed
USER vscode
